#!/bin/sh
set -eu

usage() {
    cat <<'USAGE'
Usage: ./scripts/deploy-sakura.sh [PUBLIC_DIR]

Deploy the web-facing part of Community Mapmaker Backend to Sakura Rental Server.
Keep this Git repository outside $HOME/www.

Arguments:
  PUBLIC_DIR  Web destination. Default: $HOME/www/community-mapmaker-backend

Environment:
  CMM_SAKURA_CONFIG_FILE
      Absolute path to the real config.php.
      Default: <repository>/config/config.php
USAGE
}

case "${1:-}" in
    -h|--help)
        usage
        exit 0
        ;;
esac

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
PUBLIC_DIR=${1:-"${HOME:?HOME is not set}/www/community-mapmaker-backend"}
CONFIG_FILE=${CMM_SAKURA_CONFIG_FILE:-"$REPO_ROOT/config/config.php"}

case "$PUBLIC_DIR" in
    /*) ;;
    *) PUBLIC_DIR="$(pwd)/$PUBLIC_DIR" ;;
esac

case "$CONFIG_FILE" in
    /*) ;;
    *) CONFIG_FILE="$REPO_ROOT/$CONFIG_FILE" ;;
esac

if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: config file not found: $CONFIG_FILE" >&2
    echo "Copy config/config.example.php to config/config.php and edit it first." >&2
    exit 1
fi

case "$CONFIG_FILE" in
    *"'"*)
        echo "ERROR: config path must not contain a single quote: $CONFIG_FILE" >&2
        exit 1
        ;;
esac

case "$PUBLIC_DIR/" in
    "$REPO_ROOT/"|"$REPO_ROOT/"*)
        echo "ERROR: PUBLIC_DIR must not be inside the repository." >&2
        echo "Keep the Git checkout outside the web root and deploy only runtime files to www." >&2
        exit 1
        ;;
esac

mkdir -p "$PUBLIC_DIR"

for dir in api auth admin lib; do
    rm -rf "$PUBLIC_DIR/$dir"
    cp -R "$REPO_ROOT/$dir" "$PUBLIC_DIR/$dir"
done
cp "$REPO_ROOT/bootstrap.php" "$PUBLIC_DIR/bootstrap.php"
cp "$REPO_ROOT/reset-password.html" "$PUBLIC_DIR/reset-password.html"

rm -rf "$PUBLIC_DIR/config"
mkdir -p "$PUBLIC_DIR/config"
cp "$REPO_ROOT/config/.htaccess" "$PUBLIC_DIR/config/.htaccess"
cat > "$PUBLIC_DIR/config/config.php" <<EOF_CONFIG
<?php
declare(strict_types=1);

// Generated by scripts/deploy-sakura.sh.
// The real configuration stays outside the web root.
return require '$CONFIG_FILE';
EOF_CONFIG

cat > "$PUBLIC_DIR/.htaccess" <<'EOF_HTACCESS'
Options -Indexes

<Files "bootstrap.php">
    Require all denied
</Files>
EOF_HTACCESS

cat > "$PUBLIC_DIR/lib/.htaccess" <<'EOF_LIB_HTACCESS'
Require all denied

<IfModule !mod_authz_core.c>
    Deny from all
</IfModule>
EOF_LIB_HTACCESS

find "$PUBLIC_DIR" -type d -exec chmod 755 {} \;
find "$PUBLIC_DIR" -type f -exec chmod 644 {} \;
# Sakura documents 755/705 for executable PHP programs. 755 also keeps included
# PHP files readable by the web runtime regardless of the selected PHP mode.
find "$PUBLIC_DIR" -type f -name '*.php' -exec chmod 755 {} \;

echo "Deployed to: $PUBLIC_DIR"
echo "Private config: $CONFIG_FILE"
echo "Public endpoints: admin/ api/ auth/ reset-password.html"
echo "bootstrap.php, lib/, and config/ are blocked from direct HTTP access."
